import json
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch, mm

# Load RFP data
with open("rfp_response.json", "r") as f:
    rfp_data = json.load(f)

# PDF Setup
doc = SimpleDocTemplate("NHAI_proposal.pdf", pagesize=A4,
                       rightMargin=20*mm, leftMargin=20*mm,
                       topMargin=30*mm, bottomMargin=20*mm)
styles = getSampleStyleSheet()
story = []

# Title
title_style = ParagraphStyle('CustomTitle',
                           parent=styles['Title'],
                           fontSize=18,
                           spaceAfter=30,
                           textColor=colors.darkblue,
                           alignment=1)
title = Paragraph("🏗️ RFP PROPOSAL<br/><b>NH-44 Four Laning Project</b>", title_style)
story.append(title)
story.append(Spacer(1, 20))

# Client Header
client_para = Paragraph(f"<b>Client:</b> {rfp_data['client_name']}<br/>"
                       f"<b>Project ID:</b> {rfp_data['rfp_id']}<br/>"
                       f"<b>Due:</b> {rfp_data['due_date']} | "
                       f"<b>Fit Score:</b> {rfp_data['strategic_fit_score']}%", 
                       styles['Heading1'])
story.append(client_para)
story.append(Spacer(1, 20))

# PROJECT SUMMARY - Fixed TableStyle
summary_data = [
    ['Project Value', '₹15 Cr'],
    ['Due Date', rfp_data['due_date']],
    ['Fit Score', f'{rfp_data["strategic_fit_score"]}%'],
    ['Status', '✅ AI Generated']
]
summary_table = Table(summary_data, colWidths=[2.5*inch, 2.5*inch])
summary_table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,-1), colors.lightblue),
    ('TEXTCOLOR', (0,0), (-1,0), colors.darkblue),
    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
    ('FONTSIZE', (0,0), (-1,0), 12),
    ('GRID', (0,0), (-1,-1), 1, colors.blue),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE')
]))
story.append(summary_table)
story.append(Spacer(1, 30))

# BILL OF MATERIALS - Fixed pricing table
pricing = rfp_data["pricing_summary"]
tech_data = [
    ['Product', 'SKU', 'Qty', 'Rate ₹/m', 'Total ₹', 'Match'],
    ['1.1kV Cable 240mm²', 'CABLE-1.1KV-240CU...', '1000m', '₹450', '₹4,50,000', '90%'],
    ['0.6kV Cable 185mm²', 'CABLE-0.6KV-185CU...', '500m', '₹320', '₹1,60,000', '90%'],
    ['0.4kV Cable 50mm²', 'CABLE-0.4KV-50CU...', '2000m', '₹95', '₹1,90,000', '90%'],
    ['', '', '', 'Material Total', f'₹{int(pricing["material_cost"]):,}', ''],
    ['', '', '', 'Test Costs', f'₹{int(pricing["test_cost"]):,}', ''],
    ['', '', '', '<b>GRAND TOTAL</b>', f'<b>₹{int(pricing["grand_total"]):,}</b>', '']
]

tech_table = Table(tech_data, colWidths=[1.6*inch, 1.3*inch, 0.7*inch, 0.9*inch, 1.1*inch, 0.7*inch])
tech_table.setStyle(TableStyle([
    ('BACKGROUND', (0,0), (-1,0), colors.darkblue),
    ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
    ('ALIGN', (0,0), (2,-1), 'LEFT'),
    ('ALIGN', (3,0), (-1,-1), 'RIGHT'),
    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
    ('FONTNAME', (3,6), (-1,6), 'Helvetica-Bold'),
    ('FONTSIZE', (0,0), (-1,0), 10),
    ('FONTSIZE', (0,1), (-1,-1), 9),
    ('GRID', (0,0), (-1,-1), 0.8, colors.black),
    ('BOX', (0,0), (-1,-1), 1, colors.black),
    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ('LEFTPADDING', (0,0), (-1,-1), 6),
    ('RIGHTPADDING', (0,0), (-1,-1), 6)
]))

story.append(Paragraph("📋 BILL OF MATERIALS & PRICING", styles['Heading2']))
story.append(Spacer(1, 12))
story.append(tech_table)

# Footer
footer = Paragraph("🤖 Generated by RFP Agentic AI System | Ready for NHAI Submission ✓", 
                  ParagraphStyle('Footer', parent=styles['Normal'], 
                               fontSize=9, textColor=colors.grey, alignment=1))
story.append(Spacer(1, 40))
story.append(footer)

# Build PDF
doc.build(story)
print("✅ NHAI_proposal.pdf - PROFESSIONAL FORMAT GENERATED!")
print("📄 Hackathon-ready PDF created!")
